object =open('data.txt', 'r')
print(object)
print("Name of File:",object.name)
print("Mode of File:",object.mode)
print("File readable :",object.readable())
print("File closed:",object.closed)
object.close()
print("File closed:",object.closed, object.name)
